"""Duet-review CLI command.

Provides a thin agent-callable interface to run one or both reviewer halves of
the implementer/reviewer duet against existing artifacts. No implementer stage
runs — the artifacts must already exist on disk.

Usage::

    python -m llm_client duet-review \\
        --plan-doc docs/plans/29.md \\
        --workspace /abs/path/to/repo \\
        --out runs/plan-29-review \\
        --task-title "Critique Plan 29" \\
        --task-goal "Find unverified claims and ungrounded blockers"

To also run the implementation review against a git diff, pass ``--impl-base``
(the ref to diff against) and optionally ``--impl-head`` (defaults to HEAD).
Implementer artifacts are synthesized from ``git log``/``git diff --numstat``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


def _git(*args: str, cwd: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


def _build_implement_md(workspace: str, base_ref: str, head_ref: str, impl_files: list[str]) -> str:
    commits = _git("log", "--oneline", f"{base_ref}..{head_ref}", cwd=workspace)
    diffstat = _git("diff", "--stat", f"{base_ref}..{head_ref}", cwd=workspace)
    file_list = "\n".join(f"- `{p}`" for p in impl_files) if impl_files else "_(no --impl-files passed; reviewer reads the diff)_"
    return (
        "# Implementation summary (auto-built)\n\n"
        f"This summary was generated by `python -m llm_client duet-review`. "
        f"Diff range: `{base_ref}..{head_ref}`.\n\n"
        "## Commits\n\n"
        f"```\n{commits}\n```\n\n"
        "## Diffstat\n\n"
        f"```\n{diffstat}\n```\n\n"
        "## Files to read\n\n"
        f"{file_list}\n"
    )


def _build_implement_sidecar(workspace: str, base_ref: str, head_ref: str, plan_id: str) -> dict[str, Any]:
    commits_raw = _git("log", "--format=%H %s", f"{base_ref}..{head_ref}", cwd=workspace).splitlines()
    commits: list[dict[str, Any]] = []
    for line in commits_raw:
        sha, _, msg = line.partition(" ")
        commits.append({"sha": sha[:12], "message": msg})
    numstat = _git("diff", "--numstat", f"{base_ref}..{head_ref}", cwd=workspace).splitlines()
    files_changed: list[dict[str, Any]] = []
    for line in numstat:
        parts = line.split("\t")
        if len(parts) >= 3 and parts[0].isdigit() and parts[1].isdigit():
            files_changed.append({
                "path": parts[2],
                "plus_loc": int(parts[0]),
                "minus_loc": int(parts[1]),
                "intent": "see commit messages",
            })
    return {
        "implement_id": f"impl_{head_ref}",
        "plan_id": plan_id,
        "head_commit_sha": _git("rev-parse", head_ref, cwd=workspace),
        "base_commit_sha": _git("rev-parse", base_ref, cwd=workspace),
        "files_changed": files_changed,
        "commits": commits,
        "decisions": [],
        "known_gaps": [],
    }


def _build_task(args: argparse.Namespace, workspace: str) -> dict[str, Any]:
    success_criteria = [s for s in (args.success_criteria or "").split(";") if s.strip()]
    constraints = [s for s in (args.constraints or "").split(";") if s.strip()]
    extra = _build_task_extras(args)
    return {
        "task_id": args.task_id or "duet-review",
        "title": args.task_title,
        "goal": args.task_goal,
        "workspace_path": workspace,
        "success_criteria": [s.strip() for s in success_criteria],
        "constraints": [s.strip() for s in constraints] + [
            "Do not edit any files.",
            "Verdict must be pass, revise, or block.",
        ],
        "extra": extra,
    }


def _build_task_extras(args: argparse.Namespace) -> dict[str, Any]:
    """Collect optional twin-update params into ``task["extra"]``.

    The ``twin_update`` profile's ``context_loader`` reads these keys. Keys
    absent from args produce no entry (the loader is robust to missing keys).
    Other profiles ignore ``extra`` entirely.
    """
    extra: dict[str, Any] = {}
    if getattr(args, "customer", None):
        extra["customer"] = args.customer
    if getattr(args, "ai", None):
        extra["ai"] = args.ai
    if getattr(args, "ticket_id", None):
        extra["ticket_id"] = args.ticket_id
    if complaint_file := getattr(args, "complaint_file", None):
        complaint_path = Path(complaint_file).resolve()
        if not complaint_path.is_file():
            print(f"error: --complaint-file not found: {complaint_path}", file=sys.stderr)
            sys.exit(2)
        extra["complaint_text"] = complaint_path.read_text(encoding="utf-8")
    if customer_constraints := getattr(args, "customer_constraints", None):
        extra["customer_constraints"] = [
            c.strip() for c in customer_constraints.split(";") if c.strip()
        ]
    if qa_artifact := getattr(args, "published_prod_qa_artifact", None):
        extra["published_prod_qa_artifact_path"] = qa_artifact
    return extra


def cmd_duet_review(args: argparse.Namespace) -> None:
    """Execute the ``duet-review`` subcommand.

    Resolves ``--task-family`` to a registered profile, builds the
    review task dict from CLI args (twin-update extras land in
    ``task["extra"]``), runs ``plan_review`` always, and runs
    ``implement_review`` when ``--impl-base`` is set. Writes one JSON
    artifact per stage to ``--out``. No implementer stage; this is a
    review-only entry point against existing plan-doc + git-diff inputs.
    """
    from llm_client import call_llm_structured  # type: ignore[attr-defined]
    from llm_client.workflow.duet import (
        _implement_review_prompt,
        _plan_review_prompt,
    )
    # Side-effect import: registers built-in profiles before lookup.
    import llm_client.workflow.profiles  # noqa: F401
    from llm_client.workflow.duet_registry import get_task_family

    family = get_task_family(args.task_family)

    workspace = str(Path(args.workspace).resolve())
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    plan_doc = Path(args.plan_doc).resolve()
    if not plan_doc.is_file():
        print(f"error: --plan-doc not found: {plan_doc}", file=sys.stderr)
        sys.exit(2)
    plan_md = plan_doc.read_text(encoding="utf-8")

    task = _build_task(args, workspace)
    (out_dir / "task.json").write_text(json.dumps(task, indent=2), encoding="utf-8")

    plan_sidecar = {
        "plan_id": args.plan_id or plan_doc.stem,
        "task_id": task["task_id"],
        "author_model": "external",
        "steps": [{
            "step_id": "n/a",
            "description": "Plan-doc-level review; structured atoms live in plan_md.",
            "acceptance_check": "see plan_md",
        }],
        "note": "Synthetic sidecar; the plan doc is the source of truth.",
    }

    print(f"=== plan_review ({args.reviewer_model}, family={family.name}) ===", flush=True)
    plan_review, _meta = call_llm_structured(
        args.reviewer_model,
        _plan_review_prompt(task, plan_md, plan_sidecar, family=family),
        family.plan_review_schema,
        task="duet.plan_review",
        trace_id=f"{task['task_id']}/plan_review",
        max_budget=args.max_budget,
        timeout=args.timeout,
        yolo_mode=True,
        cwd=workspace,
    )
    plan_payload = plan_review.model_dump()
    plan_payload["reviewer_model"] = args.reviewer_model
    (out_dir / "plan_review.json").write_text(
        json.dumps(plan_payload, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(f"  verdict: {plan_payload['verdict']}")
    print(f"  blockers: {len(plan_payload['blockers'])}, "
          f"nits: {len(plan_payload['nits'])}, "
          f"unverified: {len(plan_payload['unverified_claims'])}")

    if args.impl_base:
        impl_md = _build_implement_md(workspace, args.impl_base, args.impl_head, args.impl_files or [])
        impl_sidecar = _build_implement_sidecar(workspace, args.impl_base, args.impl_head, plan_sidecar["plan_id"])
        (out_dir / "implement.md").write_text(impl_md, encoding="utf-8")
        (out_dir / "implement.json").write_text(json.dumps(impl_sidecar, indent=2), encoding="utf-8")

        print(f"\n=== implement_review ({args.reviewer_model}, family={family.name}) ===", flush=True)
        impl_review, _meta = call_llm_structured(
            args.reviewer_model,
            _implement_review_prompt(task, plan_md, impl_md, impl_sidecar, family=family),
            family.implement_review_schema,
            task="duet.implement_review",
            trace_id=f"{task['task_id']}/implement_review",
            max_budget=args.max_budget,
            timeout=args.timeout,
            yolo_mode=True,
            cwd=workspace,
        )
        impl_payload = impl_review.model_dump()
        impl_payload["reviewer_model"] = args.reviewer_model
        (out_dir / "implement_review.json").write_text(
            json.dumps(impl_payload, indent=2, sort_keys=True), encoding="utf-8"
        )
        print(f"  verdict: {impl_payload['verdict']}")
        print(f"  correctness_findings: {len(impl_payload['correctness_findings'])}, "
              f"contract_violations: {len(impl_payload['contract_violations'])}, "
              f"scope_drift: {len(impl_payload['scope_drift_findings'])}")

    print(f"\nArtifacts written to: {out_dir}")


def register_parser(subparsers: Any) -> None:
    """Register the ``duet-review`` subcommand on the ``python -m llm_client`` parser.

    Wires the argparse surface (``--plan-doc``, ``--workspace``, ``--out``,
    ``--task-family``, ``--impl-base``, twin-update flags, etc.) to
    ``cmd_duet_review``. Called from ``llm_client/__main__.py``.
    """
    p = subparsers.add_parser(
        "duet-review",
        help="Review-only duet pass: run reviewer halves against existing artifacts",
        description=(
            "Runs plan_review (always) and optionally implement_review against "
            "a plan doc and git diff. No implementer stage. Outputs structured "
            "review artifacts to --out."
        ),
    )
    p.add_argument("--plan-doc", required=True, help="Path to the plan markdown document")
    p.add_argument("--workspace", required=True, help="Absolute path the agent treats as cwd")
    p.add_argument("--out", required=True, help="Output directory for review artifacts")
    p.add_argument("--task-title", required=True, help="Short title for the review task")
    p.add_argument("--task-goal", required=True, help="One-paragraph goal for what to critique")
    p.add_argument("--task-id", help="Stable task ID (default: 'duet-review')")
    p.add_argument("--plan-id", help="Stable plan ID (default: plan-doc filename stem)")
    p.add_argument(
        "--success-criteria",
        help="Semicolon-separated success criteria the reviewer checks for",
    )
    p.add_argument(
        "--constraints",
        help="Semicolon-separated constraints the reviewer enforces",
    )
    p.add_argument(
        "--reviewer-model",
        default="claude-code/sonnet",
        help="Reviewer model (default: claude-code/sonnet)",
    )
    p.add_argument(
        "--task-family",
        default="generic",
        help=(
            "Registered duet profile (default: generic). Built-ins: generic, plan_doc_review, "
            "twin_update. Use plan_doc_review when reviewing a plan document; twin_update "
            "when reviewing a customer-twin prompt/KB update."
        ),
    )
    # Twin-update specific flags. All optional; only consumed by the
    # twin_update profile's context_loader.
    p.add_argument(
        "--customer",
        help="Customer slug (twin_update profile). Routed to task.extra.customer.",
    )
    p.add_argument(
        "--ai",
        help="AI slug (twin_update profile). Routed to task.extra.ai.",
    )
    p.add_argument(
        "--ticket-id",
        help="Linear ticket ID (twin_update profile). Routed to task.extra.ticket_id.",
    )
    p.add_argument(
        "--complaint-file",
        help=(
            "Path to a file whose contents become task.extra.complaint_text "
            "(twin_update profile). Useful for multi-line complaint pastes."
        ),
    )
    p.add_argument(
        "--customer-constraints",
        help=(
            "Semicolon-separated customer-specific constraints "
            "(twin_update profile). Routed to task.extra.customer_constraints."
        ),
    )
    p.add_argument(
        "--published-prod-qa-artifact",
        help=(
            "Path to a published-prod QA artifact (twin_update profile). "
            "Routed to task.extra.published_prod_qa_artifact_path."
        ),
    )
    p.add_argument(
        "--impl-base",
        help="Git ref to diff against (e.g. origin/main). When set, also runs implement_review.",
    )
    p.add_argument("--impl-head", default="HEAD", help="Git ref for the implementation head (default: HEAD)")
    p.add_argument(
        "--impl-files",
        nargs="*",
        help="Files the reviewer should focus on (passed to implement_md narrative)",
    )
    p.add_argument("--max-budget", type=float, default=4.0, help="USD budget for the run (default: 4.0)")
    p.add_argument("--timeout", type=int, default=600, help="Per-call timeout in seconds (default: 600)")
    p.set_defaults(handler=cmd_duet_review)
